# LLM Settings
    assistant_purpose = "You are a helpful assistant specializing in retreiving information from excels files. Your task is to provide concise answers to the questions given. If the context does not provide enough information to answer a question, clearly state that you cannot answer it. All responses should be limited to one concise sentence. "
    llm_model = "open-mixtral-8x7b"
    embedding_model = "mistral-embed"

# Chat History Settings
    max_chat_history_length = 10
    database_maintainer_sleep_time = 86400

# Chat Dataprovider Settings
    vector_search_num_candidates = 150
    vector_search_limit = 4
    database = "ORION"
    collection1 = "files" # Database collection name
    special_processing = []

# Key Vault Settings
    user_assigned_client_id = "ba08be69-8030-4a1f-ae48-d8008006d2f3"
    kv_uri = "https://Dash2Labs.vault.azure.net"

# Redis Settings
[cache]
    host = "Dash2Labs.redis.cache.windows.net"
    port = 6380

# Headers
[default_headers] 
    Content-Security-Policy = "default-src 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Feature-Policy = "geolocation 'none'; microphone 'self'; camera 'none'"
    Permissions-Policy = "geolocation=(), microphone=(self), camera=()"
    Strict-Transport-Security = "max-age=36000; includeSubDomains; preload" # Set the max-age small until after testing then make it 31536000 which is a year
